table Customer
	lineageTag: c26e74a1-7b2f-4c7a-b378-459d8e682351

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 72b23f11-92bd-4d63-a754-c916f7438c68
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 7fda7c89-f7ba-4abd-8903-617eb569b030
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 5c28a508-34db-45d6-8370-ae8d41339df6
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 7602213e-5194-43c7-b081-b1d87612f05a
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: d4cbf8f8-8ef1-453d-afeb-5d8a8f0d1ac5
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: f047de48-d585-48ee-87c0-7ce5ae6eec91
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 567db049-903c-4a69-ac97-2263e6948850
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\JustinBOUVET\Downloads\AdventureWorks Sales.xlsx"), null, true),
				    Customer_Table = Source{[Item="Customer",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Customer_Table,{{"CustomerKey", Int64.Type}, {"Customer ID", type text}, {"Customer", type text}, {"City", type text}, {"State-Province", type text}, {"Country-Region", type text}, {"Postal Code", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

