table Product
	lineageTag: ad6dcb6f-082b-4e68-8df2-7a3bc121abe7

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: d5288ae7-0806-4439-bf56-e1fc5b7d51c8
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: a7b2dfb3-80b1-4526-a4f1-10c93da5828c
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 3817e1ce-d240-4929-b233-5d759aeb441d
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Standard Cost'
		dataType: double
		lineageTag: c2ea47a6-d148-49de-aa67-f10156bddb06
		summarizeBy: none
		sourceColumn: Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Color
		dataType: string
		lineageTag: 8fd6e906-f587-43a7-b38b-e0daf8e3aebe
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'List Price'
		dataType: double
		lineageTag: 8e5cfdcb-9eae-4e93-a56f-156421fd465e
		summarizeBy: none
		sourceColumn: List Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Model
		dataType: string
		lineageTag: f12dee76-a9fa-446c-ad56-4d5e65256860
		summarizeBy: none
		sourceColumn: Model

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: 0b454a90-b8e3-4d54-9491-cfe69c5716d6
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 78bd00e9-998a-4a86-a4c8-f4b989ed0198
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\JustinBOUVET\Downloads\AdventureWorks Sales.xlsx"), null, true),
				    Product_Table = Source{[Item="Product",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Product_Table,{{"ProductKey", Int64.Type}, {"SKU", type text}, {"Product", type text}, {"Standard Cost", type number}, {"Color", type text}, {"List Price", type number}, {"Model", type text}, {"Subcategory", type text}, {"Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

