table SalesOrder
	lineageTag: fd44f73a-8a8b-4fd1-9b5f-d34a8e544d0d

	column Channel
		dataType: string
		lineageTag: 8e1f3ccb-76a7-4f86-a344-df7bae1202db
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineKey
		dataType: int64
		formatString: 0
		lineageTag: 66d8bed8-204c-4ab7-9f35-e680cd9ae611
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column 'Sales Order'
		dataType: string
		lineageTag: 3a5a0817-d438-4e2e-9f9a-9f7c8a9ccfc1
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

	column 'Sales Order Line'
		dataType: string
		lineageTag: df184bf3-7ff6-4553-ad28-2f980e3ac76b
		summarizeBy: none
		sourceColumn: Sales Order Line

		annotation SummarizationSetBy = Automatic

	partition SalesOrder = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\JustinBOUVET\Downloads\AdventureWorks Sales.xlsx"), null, true),
				    SalesOrder_Table = Source{[Item="SalesOrder",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(SalesOrder_Table,{{"Channel", type text}, {"SalesOrderLineKey", Int64.Type}, {"Sales Order", type text}, {"Sales Order Line", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

